apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: clash
  labels:
    app: clash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clash
  template:
    metadata:
      labels:
        app: clash
    spec:
      containers:
        - name: clash
          image: docker.io/metacubex/mihomo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ socks5_port }}
              name: socks5
            - containerPort: {{ http_port }}
              name: http
            - containerPort: {{ control_port }}
              name: control
          volumeMounts:
            - mountPath: "/etc/clash"
              name: clash-config
          args:
            - "-f"
            - "/etc/clash/config.yaml"
      volumes:
        - name: clash-config
          configMap:
            name: clash-config
